/**
 * The portable configuration model.
 *
 * Deliberately free of Web Audio. The session coordinator, its browser
 * implementation, and the Electron main process all need these types and their
 * normalization, and none of them should have to import `graph.ts` — and with
 * it the whole `EntrainmentGraph` — to get them.
 *
 * This is also where the coercion helpers live. Disk, IPC, and localStorage are
 * all untrusted input, and all three need the same primitives to make sense of
 * whatever they actually hold.
 */

import { DEFAULT_PARAMS, sanitizeParams, TWO_TONE_MODES } from './dsp/entrainment-core.ts';
import type { EntrainmentParams } from './dsp/entrainment-core.ts';
import { NOISE_COLORS } from './dsp/noise.ts';
import type { NoiseColor } from './dsp/noise.ts';

/** Runtime list, so untrusted input can be checked against it. */
export const BED_SOURCES = ['noise', 'file'] as const;

/** Where the bed comes from: synthesised, or a file the user imported. */
export type BedSource = (typeof BED_SOURCES)[number];

/**
 * The longest a bed id may be.
 *
 * Ids are generated by this app, so any length beyond a generous bound means
 * the value did not come from here — a hand-edited file, or a renderer sending
 * something it made up.
 */
const MAX_BED_ID_LENGTH = 64;

export interface SoundscapeOptions {
  /**
   * Which generator feeds the bed.
   *
   * `color` stays meaningful either way: it is what a file bed falls back to
   * when its file cannot be resolved, which is a case that has to be
   * representable rather than an error state.
   */
  source: BedSource;
  /** The imported bed, when `source` is `file`. Null otherwise. */
  bedId: string | null;
  color: NoiseColor;
  gain: number;
  /** Notch depth in dB (positive number; applied as negative gain). */
  notchDepthDb: number;
  notchQ: number;
}

export const DEFAULT_SOUNDSCAPE: SoundscapeOptions = {
  source: 'noise',
  bedId: null,
  color: 'pink',
  gain: 0.3,
  notchDepthDb: 6,
  notchQ: 8,
};

/** Requested master level before the ceiling and headroom are applied. */
export const DEFAULT_MASTER_LEVEL = 0.7;

/**
 * Everything needed to reproduce a sound, and nothing else.
 *
 * The same shape a preset carries, minus its identity — which is what lets a
 * session record what was actually heard even after its preset is edited or
 * deleted.
 */
export interface SessionConfiguration {
  params: EntrainmentParams;
  soundscape: SoundscapeOptions;
  masterLevel: number;
}

/**
 * A detached copy, safe to store.
 *
 * `SessionConfiguration` and its nested `params` and `soundscape` are plain
 * mutable objects, so holding a reference is not a snapshot: an edit after the
 * fact would reach back and change whatever kept it. History records claim to
 * say what a session actually ran with, so they have to own their copies.
 *
 * Two levels is the whole structure — both nested objects hold only primitives.
 */
export function snapshotConfiguration(configuration: SessionConfiguration): SessionConfiguration {
  return {
    params: { ...configuration.params },
    soundscape: { ...configuration.soundscape },
    masterLevel: configuration.masterLevel,
  };
}

export function defaultConfiguration(): SessionConfiguration {
  return {
    params: { ...DEFAULT_PARAMS },
    soundscape: { ...DEFAULT_SOUNDSCAPE },
    masterLevel: DEFAULT_MASTER_LEVEL,
  };
}

// --- coercion primitives -----------------------------------------------------

export function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : {};
}

/** Undefined rather than a fallback, so the caller's own range still applies. */
export function asNumber(value: unknown): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) ? value : undefined;
}

export function asMember<T extends string>(value: unknown, allowed: readonly T[]): T | undefined {
  return typeof value === 'string' && (allowed as readonly string[]).includes(value)
    ? (value as T)
    : undefined;
}

export function clampOr(
  value: number | undefined,
  lo: number,
  hi: number,
  fallback: number,
): number {
  return value === undefined ? fallback : Math.min(hi, Math.max(lo, value));
}

// --- normalization -----------------------------------------------------------

/** A bed id, or null for anything that cannot be one. */
export function asBedId(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  if (value.length === 0 || value.length > MAX_BED_ID_LENGTH) return null;
  return value;
}

/**
 * Rebuild a soundscape from defaults, keeping only values that make sense.
 *
 * A file source with no id is incoherent rather than merely incomplete, so it
 * is resolved to the noise bed here instead of being carried forward for
 * playback to discover. Older files have neither field and read as noise,
 * which is what they were.
 */
export function normalizeSoundscape(value: unknown): SoundscapeOptions {
  const s = asRecord(value);
  const bedId = asBedId(s.bedId);
  const source = asMember(s.source, BED_SOURCES) ?? DEFAULT_SOUNDSCAPE.source;
  const usable = source === 'file' && bedId !== null;
  return {
    source: usable ? 'file' : 'noise',
    bedId: usable ? bedId : null,
    color: asMember(s.color, NOISE_COLORS) ?? DEFAULT_SOUNDSCAPE.color,
    gain: clampOr(asNumber(s.gain), 0, 1, DEFAULT_SOUNDSCAPE.gain),
    notchDepthDb: clampOr(asNumber(s.notchDepthDb), 0, 24, DEFAULT_SOUNDSCAPE.notchDepthDb),
    notchQ: clampOr(asNumber(s.notchQ), 0.1, 40, DEFAULT_SOUNDSCAPE.notchQ),
  };
}

/** Rebuild entrainment parameters from defaults through the engine's own ranges. */
export function normalizeParams(value: unknown): EntrainmentParams {
  const p = asRecord(value);
  return {
    ...DEFAULT_PARAMS,
    ...sanitizeParams({
      modulationHz: asNumber(p.modulationHz),
      carrierHz: asNumber(p.carrierHz),
      duty: asNumber(p.duty),
      edge: asNumber(p.edge),
      depth: asNumber(p.depth),
      amGain: asNumber(p.amGain),
      twoToneGain: asNumber(p.twoToneGain),
      twoToneMode: asMember(p.twoToneMode, TWO_TONE_MODES),
    }),
  };
}

export function normalizeConfiguration(value: unknown): SessionConfiguration {
  const c = asRecord(value);
  return {
    params: normalizeParams(c.params),
    soundscape: normalizeSoundscape(c.soundscape),
    masterLevel: clampOr(asNumber(c.masterLevel), 0, 1, DEFAULT_MASTER_LEVEL),
  };
}

/**
 * Float noise, and nothing wider.
 *
 * The smallest step any control can produce is 0.005 — the two level sliders —
 * so this is six orders of magnitude below the smallest real change. It exists
 * to absorb the difference between a value that made a round trip through
 * arithmetic and the literal it started as, not to forgive a change the user
 * actually made.
 */
const VALUE_EPSILON = 1e-9;

function valuesEqual(a: unknown, b: unknown): boolean {
  if (typeof a === 'number' && typeof b === 'number') return Math.abs(a - b) <= VALUE_EPSILON;
  // `bedId` is `string | null`, and the modes are string unions.
  return a === b;
}

/**
 * Compared over the union of both key sets, deliberately.
 *
 * Enumerating the fields here would mean that adding one to `EntrainmentParams`
 * or `SoundscapeOptions` and forgetting to add it here leaves a recipe field
 * that can be changed without the configuration ever counting as different —
 * silently, and in the direction that loses a user's edit. Taking the union
 * means a new field is compared the day it exists. Both sides come from the
 * normalizers or the defaults, which build fixed-shape objects, so there is no
 * incidental key to trip over.
 */
function recordsEqual(a: Record<string, unknown>, b: Record<string, unknown>): boolean {
  for (const key of new Set([...Object.keys(a), ...Object.keys(b)])) {
    if (!valuesEqual(a[key], b[key])) return false;
  }
  return true;
}

/**
 * Do two configurations describe the same sound?
 *
 * A value comparison, not a reference one: the whole point is to answer whether
 * the live recipe still matches the preset it came from, and those are always
 * different objects. Master is included because a preset stores and applies it,
 * so a preset recalled after the level moved would otherwise claim to be
 * unmodified while sounding different.
 */
export function configurationsEqual(a: SessionConfiguration, b: SessionConfiguration): boolean {
  return (
    valuesEqual(a.masterLevel, b.masterLevel) &&
    recordsEqual(
      a.params as unknown as Record<string, unknown>,
      b.params as unknown as Record<string, unknown>,
    ) &&
    recordsEqual(
      a.soundscape as unknown as Record<string, unknown>,
      b.soundscape as unknown as Record<string, unknown>,
    )
  );
}
